name: quiz_repository
publish_to: none

environment:
    sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  domain_entities:
    path: ../domain_entities
  logger: ^2.5.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib\src\assets\data\questionnaires.json