name: component_library
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  domain_entities:
    path: ../domain_entities
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  percent_indicator: ^4.2.4

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true